### ISSUE TITLE
pyshell.runString or pyshell.run is not a function

### ISSUE THREAD

**Issue by prince737** [extrabacon/python-shell#156]
The following code snippet is not working in version 1.0.4
I'm using this with electron.
 
```
var pyshell = require('python-shell')
pyshell.runString('x=1;print(x)', null, function (err, results) {
  // script finished
});
```
It gave the following error: "TypeError: pyshell.runString is not a function"

When i print pyshell in console  it shows "{PythonShell: ƒ, __esModule: true}" 
 And on expanding upto the functions, the arguments and caller of all the functions shows this:

**TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)**

Also I tried this approach:
`var PythonShell = require('python-shell');
var pyshell = new PythonShell('my_script.py');`

It gave the following error: "PythonShell is not a constructor"

Any help regarding this will be highly appretiated.

**Comment by Almenon** [comment]
Use let {PythonShell} = require('python-shell')

**Comment by MongoExpUser** [comment]
I was having the same problem but the followings solve the problem:

var **{PythonShell}** = require('python-shell')  //  or  let {**PythonShell}** = require('python-shell')

**Pyshell**.runString('x=1;print(x)', null, function (err, results) {
   // script finished
});

pyshell needs to be in **braces { } ** and **P** needs to be **capitalized** like a real **Class name** don't use **small capital p**.

**Comment by zeegit7** [comment]
It now gives me the following error when i try above fix:
TypeError: Cannot read property &#39;runString&#39; of undefined

**Comment by TumiDebrah** [comment]
It threw an error in my case  I used 
var{PythonShell} = require(‘python-shell)
PythonShell.runString(‘x=1+1;print(x)’,null,function(err){if(err) throw err; 
console.log(“finished”);
);

//please forgive the bad formatting

**Comment by Almenon** [comment]
@TumiDebrah you can use three backticks \`\`\` your code, and another three backticks \`\`\` to format it.
